version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: ess-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ess-network

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ess-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - ess-network

networks:
  ess-network:
    driver: bridge

volumes:
  mongodb_data: 