services:
  - type: web
    name: ess-backend
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
    healthCheckPath: /docs
    autoDeploy: true

databases:
  - name: ess-mongodb
    databaseName: ess_database
    plan: free 