name: Backend CI/CD

on:
  push:
    branches: [ hosting ]
    paths:
      - 'backend.py'
      - 'api/**'
      - 'requirements.txt'
      - 'utils/**'
      - 'storage/**'
      - '.github/workflows/backend.yml'
  pull_request:
    branches: [ hosting ]
    paths:
      - 'backend.py'
      - 'api/**'
      - 'requirements.txt'
      - 'utils/**'
      - 'storage/**'
      - '.github/workflows/backend.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
        
    - name: Run tests
      run: |
        pytest test_api.py --cov=./ --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/hosting'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Deploy to production
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
      run: |
        # Add your deployment commands here
        # For example, if using Heroku:
        # heroku container:push web -a your-app-name
        # heroku container:release web -a your-app-name 