name: Backend CI/CD

on:
  push:
    branches: [ hosting ]
    paths:
      - 'backend.py'
      - 'api/**'
      - 'requirements.txt'
      - 'utils/**'
      - 'storage/**'
      - '.github/workflows/backend.yml'
  pull_request:
    branches: [ hosting ]
    paths:
      - 'backend.py'
      - 'api/**'
      - 'requirements.txt'
      - 'utils/**'
      - 'storage/**'
      - '.github/workflows/backend.yml'

# Required secrets:
# - MONGO_URI: MongoDB connection string for production
# - JWT_SECRET: Secret key for JWT token generation
# - DEPLOY_KEY: SSH key for deployment (if using SSH deployment)

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ESS_env
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      PYTHONUNBUFFERED: 1  # Ensure Python output is not buffered
      MONGODB_SSL_CA_CERT: ${{ secrets.MONGODB_SSL_CA_CERT }}  # Add SSL CA cert if needed

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
        
    - name: Run tests with retry
      run: |
        # Try running tests up to 3 times
        for i in {1..3}; do
          echo "Attempt $i of 3"
          if pytest test_api.py --cov=./ --cov-report=xml; then
            exit 0
          fi
          if [ $i -lt 3 ]; then
            echo "Tests failed, waiting 10 seconds before retry..."
            sleep 10
          fi
        done
        exit 1
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: ESS_env
    if: github.ref == 'refs/heads/hosting'
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      MONGODB_SSL_CA_CERT: ${{ secrets.MONGODB_SSL_CA_CERT }}  # Add SSL CA cert if needed
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Deploy to production
      run: |
        # Add your deployment commands here
        # For example, if using Heroku:
        # heroku container:push web -a your-app-name
        # heroku container:release web -a your-app-name 