name: Test Backend

on:
  push:
    branches: [ hosting ]
    paths:
      - 'backend.py'
      - 'api/**'
      - 'requirements.txt'
      - 'utils/**'
      - 'storage/**'
      - 'test_api.py'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [ hosting ]
    paths:
      - 'backend.py'
      - 'api/**'
      - 'requirements.txt'
      - 'utils/**'
      - 'storage/**'
      - '.github/workflows/test.yml'
      - 'test_api.py'

# Required secrets:
# - MONGO_URI: MongoDB connection string for testing
# - JWT_SECRET: Secret key for JWT token generation
# - TEST_USER_EMAIL: Email for test user
# - TEST_USER_PASSWORD: Password for test user

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ESS_env
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
        
    - name: Run tests
      run: |
        pytest test_api.py --cov=./ --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true 